awakesecurity/hocker

docker2nix/Main.hs, hocker-config/Main.hs, hocker-image/Main.hs, hocker-layer/Main.hs, hocker-manifest/Main.hs, src/Data/Docker/Image/AesonHelpers.hs, src/Data/Docker/Image/Types.hs, src/Data/Docker/Image/V1/Layer.hs, src/Data/Docker/Image/V1/Types.hs, src/Data/Docker/Image/V1_2/Types.hs, src/Data/Docker/Nix.hs, src/Data/Docker/Nix/FetchDocker.hs, src/Data/Docker/Nix/Lib.hs, src/Lib.hs, src/Network/Wreq/Docker/Image/Lib.hs, src/Network/Wreq/Docker/Image/V1_2.hs, src/Network/Wreq/Docker/Registry/V2.hs, src/Network/Wreq/ErrorHandling.hs, src/Types.hs, src/Types/Exceptions.hs, src/Types/Hash.hs, src/Types/ImageName.hs, src/Types/ImageTag.hs, src/Types/URI.hs, test/Tests/Data/Docker/Image/V1.hs, test/Tests/Data/Docker/Image/V1_2.hs, test/Tests/Data/Docker/Nix/FetchDocker.hs
This change fixes each source file comment header's license field to match the Apache 2.0 license we have specified in `LICENSE` and in `hocker.cabal`.
=> AllRightsReserved => Apache-2.0

README.md, hocker-config/Main.hs, hocker-image/Main.hs, hocker-layer/Main.hs, hocker-manifest/Main.hs, src/Lib.hs, src/Types.hs
This change updates the name of the data type we use to derive option parsers, updates a few locations where `Wreq` wasn't being qualified and its own `Option` data type clashed with the new name. I also tweaked the top-level README for minor language goofiness.
=> Small cosmetic tweaks

README.md, docker2nix/README.md, src/Data/Docker/Nix/FetchDocker.hs, test/data/golden-debian:jessie.nix
Prior to this change `docker2nix` did not behave similarly to `cabal2nix` or other `*2nix` utilities. Namely it did not produce isolated and specific derivations, it produced a NixOS module-looking expression.
Outputting a NixOS module-looking expression is not technically wrong, it was simply going to complicate usage and it also made it more difficult to produce discrete `nix-build`-able expressions.
This change updates the output of `docker2nix` so that it can be called with `pkgs.callPackage` easily (assuming the `fetchdocker*` set of derivation wrappers are available on the system.)
=> Fixing docker2nix's Nix expression output

README.md, src/Data/Docker/Nix/FetchDocker.hs, src/Lib.hs, test/data/golden-debian:jessie.nix
- fetchdocker's function argument set needed to be a recursive set in
order for inherits to work correctly
- fetchDockerLayers does not take a tag argument, so only inherit the
registry, repository, and imageName attributes
The reason for this change arose from functionally testing the improved `fetchdocker` derivations in anticipation of submitting a pull request to `nixpkgs` to add them (and `hocker`).
=> Fixing the output of docker2nix

hocker.cabal
This is necessary if we specify `cabal-version:  >= 1.10`, otherwise the package will not pass validation on Hackage.
=> docker2nix section needs a default-language directive

src/Network/Wreq/Docker/Registry.hs
This reverts commit 3463253597a264ef12085cbdeb35a04531f59679.
I had an oopsie, thought I was pushing to a branch but it was `master`. I want to revert this commit and re-do the change as a PR.
=> Revert "Only accept the image manifest format"

src/Network/Wreq/Docker/Registry.hs
... we don't support image manifest lists yet and the public, official docker registry recently began serving requests by clients that say they accept it. We said we accept it but we don't actually know what to do with it yet.
=> Only accept the image manifest format

hocker.cabal, src/Network/Wreq/Docker/Image.hs
This change is being made because the `Docker-Content-Digest` value sent back by docker distribution is a hash digest from the image manifest list when only the image manifest is accepted by the client.
This issue on docker distribution tracks the regression: https://github.com/docker/distribution/issues/2395
Fixes #23
Issue #24 tracks reverting this change when the docker distribution issue is resolved.
This change also fixes a test failure caused by the tests data dir not being included in the cabal source distribution.
=> Fix response integrity check bug (#23) and fix missing tests data

nix/optparse-generic.nix, src/Hocker/Types.hs, src/Hocker/Types/Hash.hs, src/Hocker/Types/ImageName.hs, src/Hocker/Types/ImageTag.hs, src/Hocker/Types/URI.hs
This change adds `readField` implementations to the custom `ParseField` instances of the custom data types.
This change is necessary because a `readField` implementation is required as-of the `optparse-generic` release of version `1.2.3`. The `readField` implementation requirement was introduced into `optparse-generic` by [this pull request](https://github.com/Gabriel439/Haskell-Optparse-Generic-Library/pull/44).
=> Add readField implementations to custom ParseField instances

default.nix, hocker.cabal, nix/turtle.nix, release.nix, src/Data/Docker/Image/AesonHelpers.hs, src/Data/Docker/Nix/FetchDocker.hs, src/Data/Docker/Nix/Lib.hs, test/Tests/Data/Docker/Nix/FetchDocker.hs
This change switches from using `wrapProgram` to supply paths to the Nix executables to the Haskell package `nix-paths`.
There are two motivations:
1. `nix-paths` will throw a compile-time error if it cannot find a
path for any of the primary Nix executables (Nix is a dependency of
this package inside of nixpkgs too so we don't need to worry about
it anymore)
2. `wrapProgram` now throws an error if globbed file paths are given as input; which could easily be worked around but it served as impetus to solve this "The Right Way"
=> Switch to nix-paths instead of wrapProgram

default.nix, hocker.cabal, nix/17_09.nix, nix/fetchNixpkgs.nix, nix/nix-paths.nix, release.nix, src/Data/Docker/Image/AesonHelpers.hs
This change also fixes a compile error related to a datatype that is no longer re-exported by the `Data.Aeson` module in `aeson-1.1.2.0` (supplied by `nixpkgs-17.09`), requiring an import of the `Data.Aeson.Types` module and a change to the lower bound of `1.0.0.0` on the Aeson library.
=> Refactor supporting Nix code and pin to nixpkgs-17.09 latest

hocker.cabal
... because `data-dir` was incorrect and doesn't work, breaking the tests.
=> Explicitly specify the golden test data

src/Network/Wreq/Docker/Image.hs
This PR introduces two changes that fix `hocker-image`:
- as done in 63129b1, we should not check the integrity of the response when asking for the manifest due to https://github.com/docker/distribution/issues/2395
- serialization of the docker registry URI was incorrect, I think this regression was introduced into the code before we open sourced
=> Fix `hocker-image`

CHANGELOG.md, default.nix, hocker.cabal
This change bumps the patch version of `hocker` for fixes included in the following commits:
- 19c51d0
- ef9e6bd
=> 1.0.4 -> 1.0.5

hocker.cabal
=> Relax upper bound on `turtle` from `< 1.5` to `< 1.6`

nix/fetchNixpkgs.nix
... since it expects the fixed-output hash, not the intermediate hash that is used by the Nix 1.11.x logic.
Fixes #38.
=> `outputSha256` should be the hash given to builtins.fetchTarball

src/Data/Docker/Nix/Lib.hs
Starting with v1.4.5, foldl defines an "either"
that gets confused with the usual Prelude function
unless one uses a qualified import.
=> Be compatible with foldl-1.4.5.

hocker.cabal
=> Bump `hnix` dependency to a min-bound of `0.6.0`

.github/workflows/ci.yml, src/Data/Docker/Nix/FetchDocker.hs, src/Data/Docker/Nix/Lib.hs, src/Hocker/Lib.hs, src/Hocker/Types.hs, src/Hocker/Types/Exceptions.hs, src/Hocker/Types/Hash.hs, src/Hocker/Types/ImageName.hs, src/Hocker/Types/ImageTag.hs, src/Hocker/Types/URI.hs, src/Network/Wreq/Docker/Image.hs, src/Network/Wreq/Docker/Image/Lib.hs, src/Network/Wreq/Docker/Registry.hs, src/Network/Wreq/ErrorHandling.hs, test/Tests/Data/Docker/Nix/FetchDocker.hs
... because `nix` utilities will sometimes return warnings and other information to `stderr`. The type of `inprocWithErr` makes it pretty clear that we should expect a result of _either_ the stderr text _or_ the stdout text. Not both! Normally, this is fine because errors will be returned on `stderr`, however this is problematic when nix outputs warnings as the utility will end up treating them as errors.
So we need a function that will give us both and that's `procStrictWithErr`.
=> docker2nix: `inprocWithErr` -> `procStrictWithErr`

CHANGELOG.md, hocker.cabal
Changelog: https://hackage.haskell.org/package/turtle-1.6.2/changelog
There was a breaking change in 1.6.0 release, but the only use of Tutrle in this package I found is in `src/Data/Docker/Nix/Lib.hs` (to call `nixhash`), which should not be affected by this breaking change.
=> Relax upper bound on `turtle` from `< 1.6` to `< 1.7`

CHANGELOG.md, README.md, hocker-config/README.md, hocker-image/README.md, hocker-layer/README.md, hocker-manifest/README.md, src/Hocker/Types.hs, src/Network/Wreq/Docker/Registry.hs
... so you can trace / log the command line invocations without logging your secrets.
=> Add -f/--credentials-file option
